### PR TITLE
Different end screens based on game outcome, list and font styling

### LINKED ISSUE #62: General page styling

### LINKED ISSUE #70: End game screen shows whether won or lost and score

### PR DESCRIPTION
**Pull request by adriennedomingus**
Yay monospace!

closes #62 closes #70

### CODE REVIEW

**Comment by erinnachen** [comment]
@adriennedomingus could you switch over the score and lives to use a similar font?

**Comment by adriennedomingus** [comment]
@erinnachen done!

**Comment by adriennedomingus** [comment]
@erinnachen  Good to go

**Comment by erinnachen** [comment]
It seems like the fonts are not a great resolution for score display... we might have to just CSS it.

**Pull request merged**
