### PR TITLE
Collisions can occur between dino, windup, bubbles

### LINKED ISSUE #8: Detect contact between dino and windup

### PR DESCRIPTION
**Pull request by erinnachen**
* Collision is fairly generic: takes two elements and check if they collide
* When a dinosaur collides with a windup, it is reborn (unless it recently was reborn and has time in its rebornTime)
* Dinosaur has lives and they decrement with collisions, but ending the game is not yet handled
* When a windup and a bubble collide, if the bubble is still in the new phase, the bubble becomes filled and has status floating. 
* If the bubble is filled before it becomes popped, there will be an alert to rain fruit from the skies.

closes #8 , #9 and #14 

@adriennedomingus: Index.js has a bunch of logic that we should extract and somehow test. Also, I made the dinosaur jump higher so that he can pop some bubbles, so the jumping tests fail.

### CODE REVIEW

**Comment by erinnachen** [comment]
Rain those fruit down

**Comment by adriennedomingus** [comment]
Yay collisions! A couple of thoughts:

-We have some failing tests due to the change of his jump height
-The collision with the windup when it's at the top of the ceiling has to be very exact in the center of the windup - it doesn't detect when I hit its' corner
- There's no visual cue that I'm temporarily "immune"

@erinnachen thoughts? I might branch off of this to do some fruit work, it would be nice to solve a couple of those things before we merge into master

**Comment by erinnachen** [comment]
The collision function is pretty exacting. We can broaden it out by checking the range of values for element1 (the bubble). So there is a bit of a bug with bubbles in the far left corner.
I'll make a few immune images and rig them up. Definitely branch off this guy, and we'll merge stuff to master later on today.

**Comment by erinnachen** [comment]
Those tests pass now.

**Comment by adriennedomingus** [comment]
Bubbles and windups collide!

**Pull request merged**
